import fs from 'node:fs/promises';import {createRequire} from 'node:module';import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
const require=createRequire(import.meta.url);const {decode,listPDFs,matchFiles,updateBuffer}=require('../src/register.cjs');const {unzipSync,strFromU8}=require('fflate');
const [workbook,folder]=process.argv.slice(2);if(!workbook||!folder)throw Error('Usage: npm run test:samples -- /path/control.xlsx /path/PDF-folder');
const buffer=await fs.readFile(workbook),wb=decode(buffer),files=await listPDFs(folder);
const matched=wb.records.filter(r=>matchFiles(r.id,files).exact.length),suggested=wb.records.filter(r=>matchFiles(r.id,files).suggested.length);
console.log(JSON.stringify({rows:wb.records.length,duplicateRows:wb.records.filter(r=>r.duplicate).length,pdfs:files.length,exactRows:matched.length,suggestedRows:suggested.length}));
const candidate=wb.records.find(r=>r.id==='64')||wb.records[0];const updated=updateBuffer(buffer,candidate.key,'Yes','TEST ONLY — in-memory preservation check');const before=unzipSync(buffer),after=unzipSync(updated);
for(const name of Object.keys(before)){if(name!==wb.member&&Buffer.compare(before[name],after[name]))throw Error('Changed ZIP member '+name);}
const strip=s=>s.replace(new RegExp(`<c\\b[^>]*r="[DE]${candidate.row}"[^>]*(?:\\/>|>[\\s\\S]*?<\\/c>)`,'g'),'');if(strip(strFromU8(before[wb.member]))!==strip(strFromU8(after[wb.member])))throw Error('Unexpected worksheet change');console.log('PASS: only selected D/E cells changed; all other XML and ZIP members preserved. Source workbook not written.');
for(const file of files){try{const doc=await pdfjs.getDocument({data:new Uint8Array(await fs.readFile(file.path)),isEvalSupported:false}).promise;const sample=[...new Set([1,Math.ceil(doc.numPages/2),doc.numPages])];const pages=[];for(const number of sample){const page=await doc.getPage(number);const text=await page.getTextContent();pages.push({page:number,segments:text.items.filter(x=>x.str?.trim()).length,rotation:page.rotate});}console.log(JSON.stringify({file:file.name,pages:doc.numPages,samples:pages}));await doc.destroy();}catch(e){console.error(file.name+': '+e.message);process.exitCode=1;}}
