const { _electron:electron,expect }=require('@playwright/test');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const assert=require('node:assert/strict');const {decode,hash}=require('../src/register.cjs');
(async()=>{
const [source,folder]=process.argv.slice(2);if(!source||!folder)throw Error('Pass workbook and PDF folder.');const original=await fs.readFile(source);const temp=await fs.mkdtemp(path.join(os.tmpdir(),'pdf-ocr-qc-ui-'));const workbook=path.join(temp,'control.xlsx');await fs.writeFile(workbook,original);await fs.mkdir('test-results',{recursive:true});
let app;try{
app=await electron.launch({args:[path.resolve('.'),'--workbook',workbook,'--pdf-folder',folder,'--user-data-dir='+path.join(temp,'appdata')],timeout:60000});const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
await expect(page.locator('#text-count')).toContainText('segments',{timeout:60000});await expect(page.locator('#doc-title')).toHaveText('Document 64');
await page.locator('.text-segment').first().click();await expect(page.locator('.ocr-box.selected')).toHaveCount(1);await page.locator('#text-overlay').check();await expect(page.locator('#overlay')).toHaveClass(/show-text/);await page.locator('#text-overlay').uncheck();
await page.screenshot({path:'test-results/review-workspace.png'});
await page.locator('#decision').selectOption('No');await page.locator('#concerns').fill('');await page.locator('#save').click();await expect(page.locator('#notice')).toContainText('every page checked');
await page.locator('#page-checked').check();await page.getByRole('button',{name:'Incorrect text',exact:true}).click();await page.locator('#save').click();await expect(page.locator('#notice')).toContainText('Saved columns D and E');
const result=decode(await fs.readFile(workbook)).records.find(r=>r.id==='64');assert.equal(result.hasIssues,'Yes');assert.match(result.concerns,/Page 1: Incorrect/);assert.equal(hash(await fs.readFile(source)),hash(original));
await page.locator('#accuracy summary').click();await page.locator('#reference').fill('Test verified text');await page.locator('#measure').click();await expect(page.locator('#metrics')).toContainText('Character error rate');await page.locator('#accuracy summary').click();
await page.locator('#search').fill('4646');await page.locator('.queue-item').click();await expect(page.locator('#pdf-file')).toHaveValue('');await expect(page.locator('#save')).toBeDisabled();await page.locator('#pdf-file').selectOption(path.join(folder,'4644_4646_4648_4649_bookmarked.pdf'));await expect(page.locator('#text-count')).toContainText('segments',{timeout:60000});
await page.locator('#search').fill('4862');await page.locator('.queue-item').click();await page.locator('#confirm-discard').click();await expect(page.locator('#doc-title')).toHaveText('Document 4862');await expect(page.locator('#text-count')).toContainText('segments',{timeout:60000});await page.locator('#page-number').fill('65');await page.locator('#page-number').press('Tab');await expect(page.locator('#text-count')).toContainText('241',{timeout:60000});await page.screenshot({path:'test-results/rotated-page.png'});
await page.locator('#search').fill('1557');await page.locator('.queue-item').click();await expect(page.locator('#doc-title')).toHaveText('Document 1557');await expect(page.locator('#text-count')).toContainText('segments',{timeout:60000});await page.locator('#page-number').fill('134');await page.locator('#page-number').press('Tab');await expect(page.locator('#text-warning')).toBeVisible({timeout:60000});await expect(page.locator('#text-count')).toHaveText('0 text segments');
assert.deepEqual(errors,[]);console.log('PASS: UI loads actual PDFs, links selection, toggles overlay, blocks incomplete No, saves D/E with backup, calculates rates, requires combined mapping, renders rotated page and handles textless page. Original workbook unchanged.');
}finally{if(app)await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
