const crypto=require('node:crypto');
const EXPECTED=['Accessibility permission flag','Image-only PDF','Tagged PDF','Logical Reading Order','Primary language','Title','Bookmarks','Color contrast','Tagged content','Tagged annotations','Tab order','Character encoding','Tagged multimedia','Screen flicker','Scripts','Timed responses','Navigation links','Tagged form fields','Field descriptions','Figures alternate text','Nested alternate text','Associated with content','Hides annotation','Other elements alternate text','Rows','TH and TD','Headers','Regularity','Summary','List items','Lbl and LBody','Appropriate nesting'];
const EXCLUDED=new Set(['Logical Reading Order','Color contrast']);
const fields={status:'Accessibility Result',details:'Accessibility Details',reportName:'Accessibility Report',checkedAt:'Accessibility Checked On',pdfSha256:'Accessibility PDF SHA256'};
const text=s=>s.replace(/<[^>]*>/g,'').replace(/&#(x[0-9a-f]+|\d+);/gi,(_,n)=>{const c=n[0].toLowerCase()==='x'?parseInt(n.slice(1),16):Number(n);return c>0&&c<=0x10ffff?String.fromCodePoint(c):'�';}).replace(/&(amp|lt|gt|quot|apos|nbsp);/g,(_,n)=>({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '}[n])).replace(/\s+/g,' ').trim();
function unknown(details,reportName=''){return {status:'Not assessed',details,reportName,rules:[]};}
function parseReport(bytes,filename,reportName){
 if(bytes.length>2e6)return unknown('Report exceeds the supported size.',reportName);
 const html=new TextDecoder(bytes[0]===255&&bytes[1]===254?'utf-16le':bytes[0]===254&&bytes[1]===255?'utf-16be':'utf-8').decode(bytes).replace(/\0+$/,'');
 if(!/Generated by Foxit/i.test(html)||!/<h1\b[^>]*>\s*Accessibility Report\s*<\/h1>/i.test(html))return unknown('Unrecognized report format.',reportName);
 const reported=text(html.match(/<dt>\s*Filename:\s*<\/dt>\s*<dd>([\s\S]*?)<\/dd>/i)?.[1]||'');
 if(reported.toLowerCase()!==filename.toLowerCase())return unknown('Report filename does not match the PDF.',reportName);
 const rules=[];
 for(const row of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/gi)){
  const cells=[...row[1].matchAll(/<td\b[^>]*>([\s\S]*?)<\/td>/gi)].map(m=>text(m[1]));
  if(cells.length===3)rules.push({name:cells[0],status:cells[1],description:cells[2],excluded:EXCLUDED.has(cells[0])});
 }
 const names=new Set(rules.map(r=>r.name));
 if(rules.length!==32||names.size!==32||EXPECTED.some(n=>!names.has(n))||rules.some(r=>!['Passed','Passed manually','Failed','Failed manually','Needs manual check','Skipped'].includes(r.status)))return unknown('Report is incomplete or contains unsupported checks or statuses.',reportName);
 const included=rules.filter(r=>!r.excluded),failures=included.filter(r=>/^Failed/.test(r.status)),pending=included.filter(r=>['Skipped','Needs manual check'].includes(r.status));
 const status=failures.length?'Issues found':pending.length?'Needs review':'Pass—project criteria';
 const details=[`${included.filter(r=>/^Passed/.test(r.status)).length} of 30 included checks passed.`,...failures.concat(pending).map(r=>`${r.name}: ${r.status}.`),'Excluded from project criteria: '+rules.filter(r=>r.excluded).map(r=>`${r.name} (${r.status})`).join(';')+'.','Report results only; not a Section 508 certification.'].join(' ');
 return {status,details,reportName,rules};
}
function assessAttachments(attachments,filename,{corrected=false}={}){
 const reports=Object.values(attachments||{}).filter(a=>/\.accreport\.html$/i.test(a.filename||''));
 if(corrected)return unknown('Re-run Foxit on the exported PDF and open that newly checked copy as the project source. Existing reports may predate corrections.');
 if(!reports.length)return unknown('No attached Foxit accessibility report found.');
 if(reports.length!==1)return unknown('Multiple accessibility reports found; a reviewer must resolve which report applies.');
 return parseReport(reports[0].content,filename,reports[0].filename);
}
async function inspect(bytes,filename,options){
 let task;
 try{
  const pdfjs=await import('pdfjs-dist/legacy/build/pdf.mjs');
  task=pdfjs.getDocument({data:new Uint8Array(bytes),isEvalSupported:false,useSystemFonts:false});
  const doc=await task.promise;
  return {...assessAttachments(await doc.getAttachments(),filename,options),checkedAt:new Date().toISOString(),pdfSha256:crypto.createHash('sha256').update(bytes).digest('hex')};
 }catch{ return {...unknown('The attached accessibility report could not be read.'),checkedAt:new Date().toISOString(),pdfSha256:crypto.createHash('sha256').update(bytes).digest('hex')}; }
 finally{if(task)await task.destroy().catch(()=>{});}
}
module.exports={inspect,parseReport,assessAttachments,fields,EXPECTED};
